---
version: 1
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG            
        formatter: simple
        filename: logs/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 200
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR            
        formatter: simple
        filename: logs/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    cherrypy.access:
        level: ERROR
        handlers: [console]
        propagate: no

    task:
        level: DEBUG
        handlers: [console, info_file_handler]
        propagate: no

    site:
        level: DEBUG
        handlers: [console, info_file_handler]
        propagate: no

root:
    level: DEBUG 
    handlers: [console, info_file_handler, error_file_handler]
